server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: xjh990403
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: itcast
    password: 123321
    virtual-host: /
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo